//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.27 at 12:48:17 PM CET 
//


package et5.service.route;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the et5.service.route package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: et5.service.route
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link Route.Matches }
     * 
     */
    public Route.Matches createRouteMatches() {
        return new Route.Matches();
    }

    /**
     * Create an instance of {@link Route.Matches.Match }
     * 
     */
    public Route.Matches.Match createRouteMatchesMatch() {
        return new Route.Matches.Match();
    }

    /**
     * Create an instance of {@link Route.Matches.Match.Goals }
     * 
     */
    public Route.Matches.Match.Goals createRouteMatchesMatchGoals() {
        return new Route.Matches.Match.Goals();
    }

    /**
     * Create an instance of {@link Route.Matches.Match.Cards }
     * 
     */
    public Route.Matches.Match.Cards createRouteMatchesMatchCards() {
        return new Route.Matches.Match.Cards();
    }

}
