package et5.client.et5.service.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FootServiceService", targetNamespace = "http://web.service.et5/", wsdlLocation = "http://localhost:8090/ws?wsdl")
public class FootServiceService
    extends Service
{

    private final static URL FOOTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FOOTSERVICESERVICE_EXCEPTION;
    private final static QName FOOTSERVICESERVICE_QNAME = new QName("http://web.service.et5/", "FootServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FOOTSERVICESERVICE_WSDL_LOCATION = url;
        FOOTSERVICESERVICE_EXCEPTION = e;
    }

    public FootServiceService() {
        super(__getWsdlLocation(), FOOTSERVICESERVICE_QNAME);
    }

    public FootServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FOOTSERVICESERVICE_QNAME, features);
    }

    public FootServiceService(URL wsdlLocation) {
        super(wsdlLocation, FOOTSERVICESERVICE_QNAME);
    }

    public FootServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FOOTSERVICESERVICE_QNAME, features);
    }

    public FootServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FootServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FootService
     */
    @WebEndpoint(name = "FootServicePort")
    public FootService getFootServicePort() {
        return super.getPort(new QName("http://web.service.et5/", "FootServicePort"), FootService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FootService
     */
    @WebEndpoint(name = "FootServicePort")
    public FootService getFootServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.service.et5/", "FootServicePort"), FootService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FOOTSERVICESERVICE_EXCEPTION!= null) {
            throw FOOTSERVICESERVICE_EXCEPTION;
        }
        return FOOTSERVICESERVICE_WSDL_LOCATION;
    }

}
