package et5.client.et5.service.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FootService", targetNamespace = "http://web.service.et5/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FootService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRouteTeamSynchronous", targetNamespace = "http://web.service.et5/", className = "et5.service.web.GetRouteTeamSynchronous")
    @ResponseWrapper(localName = "getRouteTeamSynchronousResponse", targetNamespace = "http://web.service.et5/", className = "et5.service.web.GetRouteTeamSynchronousResponse")
    @Action(input = "http://web.service.et5/FootService/getRouteTeamSynchronousRequest", output = "http://web.service.et5/FootService/getRouteTeamSynchronousResponse")
    public String getRouteTeamSynchronous(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRouteTeamAsynchronous", targetNamespace = "http://web.service.et5/", className = "et5.service.web.GetRouteTeamAsynchronous")
    @ResponseWrapper(localName = "getRouteTeamAsynchronousResponse", targetNamespace = "http://web.service.et5/", className = "et5.service.web.GetRouteTeamAsynchronousResponse")
    @Action(input = "http://web.service.et5/FootService/getRouteTeamAsynchronousRequest", output = "http://web.service.et5/FootService/getRouteTeamAsynchronousResponse")
    public int getRouteTeamAsynchronous(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
